version: '2'
services:
  dbdata:
    image: busybox
    container_name: dbdata
    volumes:
      - /var/lib/mysql
  db:
    image: mysql:5.7.17
    container_name: db
    volumes_from:
      - dbdata
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      #- MYSQL_ALLOW_EMPTY_PASSWORD
      #- MYSQL_RANDOM_ROOT_PASSWORD
    privileged: true
  web:
    build: .
    #command: bundle exec rails s -p 3000 -b '0.0.0.0'
    command: /bin/bash -c "nginx && bundle exec unicorn -c config/unicorn.rb -D && while true; do sleep 10000; done"
    container_name: web
    volumes:
      - .:/railsapp
    ports:
      - "80:80"
    depends_on:
      - db
    privileged: true
